### PR TITLE
Added getting jobs added within a week.

### PR DESCRIPTION
**Pull request by ab-elhaddad**

### CODE REVIEW

**Review by Mahmoudgalalz — CHANGES_REQUESTED** [review]
This code, full of bugs

@ab-elhaddad 

Basically, it accepts any type of request which is wrong
Also I mentioned that we can set span without date, which will take a date of the current data of the request
a lot of unnecessary `if`, bad typs with undefined, hard way to set the dates 

If there's smth you want help with, feel free to ask me

**Comment by ab-elhaddad** [comment]
@Mahmoudgalalz 
In this commit I have fixed the following issues:
- Make it accepts only the GET requests
- Added the functionality to accept span without date, and deal with the current date of the request
- Refactored the code and made it simpler and easier to read

**Comment by Mahmoudgalalz** [comment]
@ab-elhaddad why I did added type ?!

as any param will be added it will be ignored to the request not the code, which is better validation code

@ab-elhaddad Thanks for this improvement

**Comment by ab-elhaddad** [comment]
yes, I see. thanks for the info.
@Mahmoudgalalz

**Pull request merged**
